from . import help
from . import start
from . import Fargona
from . import toshkent
from . import andijon
from . import namangan
from . import navoiy
from . import samarqand
from . import buhoro
from . import jizzax
from . import inline_vaqt
from . import echo